// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

// Defines values for UserRole.
const (
	ACCESSTOREPORTS             UserRole = "ACCESS_TO_REPORTS"
	ACCOUNTHOLDER               UserRole = "ACCOUNT_HOLDER"
	ADMIN                       UserRole = "ADMIN"
	APPMANAGER                  UserRole = "APP_MANAGER"
	CLOUDMANAGEDAPPDISTRIBUTION UserRole = "CLOUD_MANAGED_APP_DISTRIBUTION"
	CLOUDMANAGEDDEVELOPERID     UserRole = "CLOUD_MANAGED_DEVELOPER_ID"
	CREATEAPPS                  UserRole = "CREATE_APPS"
	CUSTOMERSUPPORT             UserRole = "CUSTOMER_SUPPORT"
	DEVELOPER                   UserRole = "DEVELOPER"
	FINANCE                     UserRole = "FINANCE"
	GENERATEINDIVIDUALKEYS      UserRole = "GENERATE_INDIVIDUAL_KEYS"
	MARKETING                   UserRole = "MARKETING"
	SALES                       UserRole = "SALES"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case ACCESSTOREPORTS:
		return true
	case ACCOUNTHOLDER:
		return true
	case ADMIN:
		return true
	case APPMANAGER:
		return true
	case CLOUDMANAGEDAPPDISTRIBUTION:
		return true
	case CLOUDMANAGEDDEVELOPERID:
		return true
	case CREATEAPPS:
		return true
	case CUSTOMERSUPPORT:
		return true
	case DEVELOPER:
		return true
	case FINANCE:
		return true
	case GENERATEINDIVIDUALKEYS:
		return true
	case MARKETING:
		return true
	case SALES:
		return true
	default:
		return false
	}
}

// AppRelationship defines model for AppRelationship.
type AppRelationship struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

// User defines model for User.
type User struct {
	Attributes    UserAttributes     `json:"attributes"`
	Id            string             `json:"id"`
	Relationships *UserRelationships `json:"relationships,omitempty"`
	Type          *string            `json:"type,omitempty"`
}

// UserAttributes defines model for UserAttributes.
type UserAttributes struct {
	AllAppsVisible            *bool       `json:"allAppsVisible,omitempty"`
	FirstName                 *string     `json:"firstName,omitempty"`
	LastName                  *string     `json:"lastName,omitempty"`
	ProvisioningAllowed       *bool       `json:"provisioningAllowed,omitempty"`
	Roles                     *[]UserRole `json:"roles,omitempty"`
	UserHasAcceptedInvitation *bool       `json:"userHasAcceptedInvitation,omitempty"`
	Username                  *string     `json:"username,omitempty"`
}

// UserInvitation defines model for UserInvitation.
type UserInvitation struct {
	Attributes    UserInvitationAttributes     `json:"attributes"`
	Id            string                       `json:"id"`
	Relationships *UserInvitationRelationships `json:"relationships,omitempty"`
	Type          *string                      `json:"type,omitempty"`
}

// UserInvitationAttributes defines model for UserInvitationAttributes.
type UserInvitationAttributes struct {
	AllAppsVisible      *bool       `json:"allAppsVisible,omitempty"`
	Email               *string     `json:"email,omitempty"`
	FirstName           *string     `json:"firstName,omitempty"`
	LastName            *string     `json:"lastName,omitempty"`
	ProvisioningAllowed *bool       `json:"provisioningAllowed,omitempty"`
	Roles               *[]UserRole `json:"roles,omitempty"`
}

// UserInvitationCreateRequest defines model for UserInvitationCreateRequest.
type UserInvitationCreateRequest struct {
	Data UserInvitationCreateRequestData `json:"data"`
}

// UserInvitationCreateRequestAttributes defines model for UserInvitationCreateRequestAttributes.
type UserInvitationCreateRequestAttributes struct {
	AllAppsVisible      *bool      `json:"allAppsVisible,omitempty"`
	Email               string     `json:"email"`
	FirstName           string     `json:"firstName"`
	LastName            string     `json:"lastName"`
	ProvisioningAllowed *bool      `json:"provisioningAllowed,omitempty"`
	Roles               []UserRole `json:"roles"`
}

// UserInvitationCreateRequestData defines model for UserInvitationCreateRequestData.
type UserInvitationCreateRequestData struct {
	Attributes    UserInvitationCreateRequestAttributes     `json:"attributes"`
	Relationships *UserInvitationCreateRequestRelationships `json:"relationships,omitempty"`
	Type          string                                    `json:"type"`
}

// UserInvitationCreateRequestRelationships defines model for UserInvitationCreateRequestRelationships.
type UserInvitationCreateRequestRelationships struct {
	// VisibleApps Write relationship to visible apps, used in API requests.
	VisibleApps *UserVisibleAppsLinkages `json:"visibleApps,omitempty"`
}

// UserInvitationRelationships defines model for UserInvitationRelationships.
type UserInvitationRelationships struct {
	// VisibleApps Read-only relationship to visible apps, returned in API responses.
	VisibleApps *UserVisibleAppsRelationship `json:"visibleApps,omitempty"`
}

// UserInvitationResponse defines model for UserInvitationResponse.
type UserInvitationResponse struct {
	Data UserInvitation `json:"data"`
}

// UserRelationships defines model for UserRelationships.
type UserRelationships struct {
	// VisibleApps Read-only relationship to visible apps, returned in API responses.
	VisibleApps *UserVisibleAppsRelationship `json:"visibleApps,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	Data UserUpdateRequestData `json:"data"`
}

// UserUpdateRequestAttributes defines model for UserUpdateRequestAttributes.
type UserUpdateRequestAttributes struct {
	AllAppsVisible      *bool       `json:"allAppsVisible,omitempty"`
	ProvisioningAllowed *bool       `json:"provisioningAllowed,omitempty"`
	Roles               *[]UserRole `json:"roles,omitempty"`
}

// UserUpdateRequestData defines model for UserUpdateRequestData.
type UserUpdateRequestData struct {
	Attributes    UserUpdateRequestAttributes     `json:"attributes"`
	Id            string                          `json:"id"`
	Relationships *UserUpdateRequestRelationships `json:"relationships,omitempty"`
	Type          string                          `json:"type"`
}

// UserUpdateRequestRelationships defines model for UserUpdateRequestRelationships.
type UserUpdateRequestRelationships struct {
	// VisibleApps Write relationship to visible apps, used in API requests.
	VisibleApps *UserVisibleAppsLinkages `json:"visibleApps,omitempty"`
}

// UserVisibleAppsLinkages Write relationship to visible apps, used in API requests.
type UserVisibleAppsLinkages struct {
	Data []AppRelationship `json:"data"`
}

// UserVisibleAppsRelationship Read-only relationship to visible apps, returned in API responses.
type UserVisibleAppsRelationship struct {
	Data *[]AppRelationship `json:"data,omitempty"`
}

// CreateUserInvitationJSONRequestBody defines body for CreateUserInvitation for application/json ContentType.
type CreateUserInvitationJSONRequestBody = UserInvitationCreateRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdateRequest
