// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"time"
)

// Defines values for BundleIdPlatform.
const (
	IOS   BundleIdPlatform = "IOS"
	MACOS BundleIdPlatform = "MAC_OS"
)

// Valid indicates whether the value is a known member of the BundleIdPlatform enum.
func (e BundleIdPlatform) Valid() bool {
	switch e {
	case IOS:
		return true
	case MACOS:
		return true
	default:
		return false
	}
}

// Defines values for DeviceClass.
const (
	APPLETV        DeviceClass = "APPLE_TV"
	APPLEVISIONPRO DeviceClass = "APPLE_VISION_PRO"
	APPLEWATCH     DeviceClass = "APPLE_WATCH"
	IPAD           DeviceClass = "IPAD"
	IPHONE         DeviceClass = "IPHONE"
	IPOD           DeviceClass = "IPOD"
	MAC            DeviceClass = "MAC"
)

// Valid indicates whether the value is a known member of the DeviceClass enum.
func (e DeviceClass) Valid() bool {
	switch e {
	case APPLETV:
		return true
	case APPLEVISIONPRO:
		return true
	case APPLEWATCH:
		return true
	case IPAD:
		return true
	case IPHONE:
		return true
	case IPOD:
		return true
	case MAC:
		return true
	default:
		return false
	}
}

// Defines values for DeviceStatus.
const (
	DISABLED DeviceStatus = "DISABLED"
	ENABLED  DeviceStatus = "ENABLED"
)

// Valid indicates whether the value is a known member of the DeviceStatus enum.
func (e DeviceStatus) Valid() bool {
	switch e {
	case DISABLED:
		return true
	case ENABLED:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	ACCESSTOREPORTS             UserRole = "ACCESS_TO_REPORTS"
	ACCOUNTHOLDER               UserRole = "ACCOUNT_HOLDER"
	ADMIN                       UserRole = "ADMIN"
	APPMANAGER                  UserRole = "APP_MANAGER"
	CLOUDMANAGEDAPPDISTRIBUTION UserRole = "CLOUD_MANAGED_APP_DISTRIBUTION"
	CLOUDMANAGEDDEVELOPERID     UserRole = "CLOUD_MANAGED_DEVELOPER_ID"
	CREATEAPPS                  UserRole = "CREATE_APPS"
	CUSTOMERSUPPORT             UserRole = "CUSTOMER_SUPPORT"
	DEVELOPER                   UserRole = "DEVELOPER"
	FINANCE                     UserRole = "FINANCE"
	GENERATEINDIVIDUALKEYS      UserRole = "GENERATE_INDIVIDUAL_KEYS"
	MARKETING                   UserRole = "MARKETING"
	SALES                       UserRole = "SALES"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case ACCESSTOREPORTS:
		return true
	case ACCOUNTHOLDER:
		return true
	case ADMIN:
		return true
	case APPMANAGER:
		return true
	case CLOUDMANAGEDAPPDISTRIBUTION:
		return true
	case CLOUDMANAGEDDEVELOPERID:
		return true
	case CREATEAPPS:
		return true
	case CUSTOMERSUPPORT:
		return true
	case DEVELOPER:
		return true
	case FINANCE:
		return true
	case GENERATEINDIVIDUALKEYS:
		return true
	case MARKETING:
		return true
	case SALES:
		return true
	default:
		return false
	}
}

// AppRelationship defines model for AppRelationship.
type AppRelationship struct {
	Id   string `json:"id"`
	Type string `json:"type"`
}

// BundleIdPlatform defines model for BundleIdPlatform.
type BundleIdPlatform string

// Device defines model for Device.
type Device struct {
	Attributes DeviceAttributes `json:"attributes"`
	Id         string           `json:"id"`
	Type       *string          `json:"type,omitempty"`
}

// DeviceAttributes defines model for DeviceAttributes.
type DeviceAttributes struct {
	AddedDate   *time.Time        `json:"addedDate,omitempty"`
	DeviceClass *DeviceClass      `json:"deviceClass,omitempty"`
	Model       *string           `json:"model,omitempty"`
	Name        *string           `json:"name,omitempty"`
	Os          *string           `json:"os,omitempty"`
	Platform    *BundleIdPlatform `json:"platform,omitempty"`
	Status      *DeviceStatus     `json:"status,omitempty"`
	Udid        *string           `json:"udid,omitempty"`
}

// DeviceClass defines model for DeviceClass.
type DeviceClass string

// DeviceCreateRequest defines model for DeviceCreateRequest.
type DeviceCreateRequest struct {
	Data DeviceCreateRequestData `json:"data"`
}

// DeviceCreateRequestAttributes defines model for DeviceCreateRequestAttributes.
type DeviceCreateRequestAttributes struct {
	Name     string           `json:"name"`
	Platform BundleIdPlatform `json:"platform"`
	Udid     string           `json:"udid"`
}

// DeviceCreateRequestData defines model for DeviceCreateRequestData.
type DeviceCreateRequestData struct {
	Attributes DeviceCreateRequestAttributes `json:"attributes"`
	Type       string                        `json:"type"`
}

// DeviceResponse defines model for DeviceResponse.
type DeviceResponse struct {
	Data Device `json:"data"`
}

// DeviceStatus defines model for DeviceStatus.
type DeviceStatus string

// DeviceUpdateRequest defines model for DeviceUpdateRequest.
type DeviceUpdateRequest struct {
	Data DeviceUpdateRequestData `json:"data"`
}

// DeviceUpdateRequestAttributes defines model for DeviceUpdateRequestAttributes.
type DeviceUpdateRequestAttributes struct {
	Name   *string       `json:"name,omitempty"`
	Status *DeviceStatus `json:"status,omitempty"`
}

// DeviceUpdateRequestData defines model for DeviceUpdateRequestData.
type DeviceUpdateRequestData struct {
	Attributes DeviceUpdateRequestAttributes `json:"attributes"`
	Id         string                        `json:"id"`
	Type       string                        `json:"type"`
}

// User defines model for User.
type User struct {
	Attributes    UserAttributes     `json:"attributes"`
	Id            string             `json:"id"`
	Relationships *UserRelationships `json:"relationships,omitempty"`
	Type          *string            `json:"type,omitempty"`
}

// UserAttributes defines model for UserAttributes.
type UserAttributes struct {
	AllAppsVisible            *bool       `json:"allAppsVisible,omitempty"`
	FirstName                 *string     `json:"firstName,omitempty"`
	LastName                  *string     `json:"lastName,omitempty"`
	ProvisioningAllowed       *bool       `json:"provisioningAllowed,omitempty"`
	Roles                     *[]UserRole `json:"roles,omitempty"`
	UserHasAcceptedInvitation *bool       `json:"userHasAcceptedInvitation,omitempty"`
	Username                  *string     `json:"username,omitempty"`
}

// UserInvitation defines model for UserInvitation.
type UserInvitation struct {
	Attributes    UserInvitationAttributes     `json:"attributes"`
	Id            string                       `json:"id"`
	Relationships *UserInvitationRelationships `json:"relationships,omitempty"`
	Type          *string                      `json:"type,omitempty"`
}

// UserInvitationAttributes defines model for UserInvitationAttributes.
type UserInvitationAttributes struct {
	AllAppsVisible      *bool       `json:"allAppsVisible,omitempty"`
	Email               *string     `json:"email,omitempty"`
	FirstName           *string     `json:"firstName,omitempty"`
	LastName            *string     `json:"lastName,omitempty"`
	ProvisioningAllowed *bool       `json:"provisioningAllowed,omitempty"`
	Roles               *[]UserRole `json:"roles,omitempty"`
}

// UserInvitationCreateRequest defines model for UserInvitationCreateRequest.
type UserInvitationCreateRequest struct {
	Data UserInvitationCreateRequestData `json:"data"`
}

// UserInvitationCreateRequestAttributes defines model for UserInvitationCreateRequestAttributes.
type UserInvitationCreateRequestAttributes struct {
	AllAppsVisible      *bool      `json:"allAppsVisible,omitempty"`
	Email               string     `json:"email"`
	FirstName           string     `json:"firstName"`
	LastName            string     `json:"lastName"`
	ProvisioningAllowed *bool      `json:"provisioningAllowed,omitempty"`
	Roles               []UserRole `json:"roles"`
}

// UserInvitationCreateRequestData defines model for UserInvitationCreateRequestData.
type UserInvitationCreateRequestData struct {
	Attributes    UserInvitationCreateRequestAttributes     `json:"attributes"`
	Relationships *UserInvitationCreateRequestRelationships `json:"relationships,omitempty"`
	Type          string                                    `json:"type"`
}

// UserInvitationCreateRequestRelationships defines model for UserInvitationCreateRequestRelationships.
type UserInvitationCreateRequestRelationships struct {
	// VisibleApps Write relationship to visible apps, used in API requests.
	VisibleApps *UserVisibleAppsLinkages `json:"visibleApps,omitempty"`
}

// UserInvitationRelationships defines model for UserInvitationRelationships.
type UserInvitationRelationships struct {
	// VisibleApps Read-only relationship to visible apps, returned in API responses.
	VisibleApps *UserVisibleAppsRelationship `json:"visibleApps,omitempty"`
}

// UserInvitationResponse defines model for UserInvitationResponse.
type UserInvitationResponse struct {
	Data UserInvitation `json:"data"`
}

// UserRelationships defines model for UserRelationships.
type UserRelationships struct {
	// VisibleApps Read-only relationship to visible apps, returned in API responses.
	VisibleApps *UserVisibleAppsRelationship `json:"visibleApps,omitempty"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Data User `json:"data"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserUpdateRequest defines model for UserUpdateRequest.
type UserUpdateRequest struct {
	Data UserUpdateRequestData `json:"data"`
}

// UserUpdateRequestAttributes defines model for UserUpdateRequestAttributes.
type UserUpdateRequestAttributes struct {
	AllAppsVisible      *bool       `json:"allAppsVisible,omitempty"`
	ProvisioningAllowed *bool       `json:"provisioningAllowed,omitempty"`
	Roles               *[]UserRole `json:"roles,omitempty"`
}

// UserUpdateRequestData defines model for UserUpdateRequestData.
type UserUpdateRequestData struct {
	Attributes    UserUpdateRequestAttributes     `json:"attributes"`
	Id            string                          `json:"id"`
	Relationships *UserUpdateRequestRelationships `json:"relationships,omitempty"`
	Type          string                          `json:"type"`
}

// UserUpdateRequestRelationships defines model for UserUpdateRequestRelationships.
type UserUpdateRequestRelationships struct {
	// VisibleApps Write relationship to visible apps, used in API requests.
	VisibleApps *UserVisibleAppsLinkages `json:"visibleApps,omitempty"`
}

// UserVisibleAppsLinkages Write relationship to visible apps, used in API requests.
type UserVisibleAppsLinkages struct {
	Data []AppRelationship `json:"data"`
}

// UserVisibleAppsRelationship Read-only relationship to visible apps, returned in API responses.
type UserVisibleAppsRelationship struct {
	Data *[]AppRelationship `json:"data,omitempty"`
}

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = DeviceCreateRequest

// UpdateDeviceJSONRequestBody defines body for UpdateDevice for application/json ContentType.
type UpdateDeviceJSONRequestBody = DeviceUpdateRequest

// CreateUserInvitationJSONRequestBody defines body for CreateUserInvitation for application/json ContentType.
type CreateUserInvitationJSONRequestBody = UserInvitationCreateRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdateRequest
